project:
  type: website
  output-dir: docs

website:
  title: "Rebecca Larsen"
  navbar: 
    right: 
    - href: index.qmd
      text: Home 
    - href: about.qmd
      text: About 
    - href: CV.pdf
      text: CV 
    - text: Assignments 
      menu: 
      - href: Lab01.html
        text: Lab1
      - href: Lab02.html 
        text: Lab2
      - href: Assignment02.html 
        text: Assignment2


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



