project:
  type: website
  output-dir: docs

website:
  title: "r-larsen.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Assignments 
         menu: 
          - href: about.qmd
            text: assignment1


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



