project:
  type: website
  output-dir: docs

website:
  title: "r-larsen.github.io"
  navbar: 
    right: 
    - href: index.qmd
      text: Home 
    - href: about.qmd
      text: About 
    - href: cv.pdf
      text: CV 
    - text: Assignments 
      menu: 
      - href: Lab01.qmd
        text: Lab1
      - href: Lab02.qmd 
        text: Lab2



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



