project:
  type: website
  output-dir: docs

website:
  title: "Rebecca Larsen"
  navbar: 
    right: 
    - href: index.qmd
      text: Home 
    - href: about.qmd
      text: About 
    - href: CV_2.2023.pdf
      text: CV 
    - text: Assignments 
      menu: 
      - href: Assignment01.html 
        text: Assignment1
      - href: AssignmentTwo.Rmd 
        text: Assignment2
      - href: Assignment03.html 
        text: Assignment3
      - href: Assignment05.pdf 
        text: Assignment5


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
    



